spring.application.name=capacity-service

# Configuracion de MySQL
spring.r2dbc.url=r2dbc:mysql://${CAPACITY_MYSQL_HOST}:${CAPACITY_MYSQL_PORT}/${CAPACITY_MYSQL_DATABASE}
spring.r2dbc.username=${CAPACITY_MYSQL_USERNAME}
spring.r2dbc.password=${CAPACITY_MYSQL_PASSWORD}

# Ejecutar scripts de inicializacion
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Configuracion de Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
